name: civet3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - iqtree>=2.1
  - minimap2>=2.17
  - python=3.9
  - snakemake-minimal
  - cov-ert::jclusterfunk
  - gofasta
variables:
  DATADIR: '/cephfs/covid/bham/results/phylogenetics/latest/civet/cog'

# civet now requires conda version 4.9 or later