name: civet
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - iqtree
  - minimap2
  - pip=19.3.1
  - python=3.6
  - snakemake-minimal=5.13
  - cov-ert::jclusterfunk
  - gofasta

