name: civet3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - iqtree>=2.1
  - minimap2>=2.17
  - python=3.9
  - snakemake-minimal=6.1
  - cov-ert::jclusterfunk
  - gofasta

